var Constants = {
  PROFILE_RECEIVED: "PROFILE_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  USER_UPDATED: "USER_UPDATED",
  SESSION_REMOVED: "SESSION_REMOVED",

  LIKES_RECEIVED: "LIKES_RECEIVED",
  LIKE_RECEIVED: "LIKE_RECEIVED",
  LIKE_REMOVED: "LIKE_REMOVED",

  INTERESTS_RECEIVED: "INTERESTS_RECEIVED",
  INTEREST_RECEIVED: "INTEREST_RECEIVED",
  INTEREST_REMOVED: "INTEREST_REMOVED",

  MESSAGES_RECEIVED: "MESSAGES_RECEIVED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_REMOVED: "MESSAGE_REMOVED",

  SEARCH_PARAMS_RECEIVED: "SEARCH_PARAMS_RECEIVED",
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED"
}

module.exports = Constants;
