var Constants = {
  PROFILE_RECEIVED: "PROFILE_RECEIVED",
  INTERESTS_RECEIVED: "INTERESTS_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  USER_UPDATED: "USER_UPDATED",
  SEARCH_PARAMS_RECEIVED: "SEARCH_PARAMS_RECEIVED",

  MY_LIKES_RECEIVED: "MY_LIKES_RECEIVED",
  MY_LIKE_RECEIVED: "MY_LIKE_RECEIVED",
  MY_LIKE_UPDATED: "MY_LIKE_UPDATED",
  MY_FANS_RECEIVED: "MY_FANS_RECEIVED",
  MY_FAN_RECEIVED: "MY_FAN_RECEIVED",
  MY_FAN_UPDATED: "MY_FAN_UPDATED",

  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED"
}

module.exports = Constants;
