var Constants = {
  PROFILE_RECEIVED: "PROFILE_RECEIVED",
  INTERESTS_RECEIVED: "INTERESTS_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  USER_UPDATED: "USER_UPDATED"
}

module.exports = Constants;
